<a href="https://colab.research.google.com/github/MadeaRiggs/AIPlanet-Deep-Learning-projects/blob/main/AIPlanet_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors are multi-dimensional arrays with a uniform type (called a `dtype`).  You can see all supported `dtypes` at `tf.dtypes.DType`.

All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.

In [ ]:
import tensorflow as tf
import numpy as np

* A scalar is a single number
* A vector is an array of numbers.
* A matrix is a 2-D array
* A tensor is a n-dimensional array with n >2

### Scalar  - Rank 0 Tensor
A scalar contains a single value, and no "axes".

In [ ]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


### Vector - Rank 1 Tensor
A "vector" or "rank-1" tensor is like a list of values. A vector has 1-axis:

In [ ]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


### Matrix - Rank 2 Tensor
A "matrix" or "rank-2" tensor has 2-axes:

In [ ]:
# If we want to be specific, we can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


<table>
<tr>
  <th>A scalar, shape: <code>[]</code></th>
  <th>A vector, shape: <code>[3]</code></th>
  <th>A matrix, shape: <code>[3, 2]</code></th>
</tr>
<tr>
  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/scalar.png?raw=1" alt="A scalar, the number 4" />
  </td>

  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/vector.png?raw=1" alt="The line with 3 sections, each one containing a number."/>
  </td>
  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/matrix.png?raw=1" alt="A 3x2 grid, with each cell containing a number.">
  </td>
</tr>
</table>


In [ ]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
                            [[0, 1, 2, 3, 4],
                            [5, 6, 7, 8, 9]],
                            [[10, 11, 12, 13, 14],
                            [15, 16, 17, 18, 19]],
                            [[20, 21, 22, 23, 24],
                            [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


<table>
<tr>
  <th colspan=3>A 3-axis tensor, shape: <code>[3, 2, 5]</code></th>
<tr>
<tr>
  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/3-axis_numpy.png?raw=1"/>
  </td>
  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/3-axis_front.png?raw=1"/>
  </td>

  <td>
   <img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/3-axis_block.png?raw=1"/>
  </td>
</tr>

</table>

In [ ]:
#converting tensor to numpy array using np.array
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
#converting tensor to numpy array using .numpy
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
#math operations on tensors
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
#element-wise multiplication 
print(tf.multiply(a, b), "\n")
#matrix multiplication
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
#or
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



####**Dimension:** 

Let’s take an example of box to explain this. A simple box can have three dimensions width, length and depth (or height). Similarly, in data science we will be working “N” dimensional datasets. “N” could be any number.

####**Indexes:** 

Indexes are required to access an element in a Data Structure.



In [ ]:
a= [1,2,3,4]
#access using a single index
a[2]

3

In [ ]:
dd= [
    [1,2,3],
     [4,5,6],
     [7,8,9]
]
#use two indexes to locate the specific element.
dd[0][2]

3

#### **Rank:**


The rank of a tensor refers to the number of dimensions present within the tensor.


**Rank & Indexes:**

The rank of a tensor tells us how many indexes are required to access (refer to) a specific data element contained within the tensor data structure.

A tensor's rank tells us how many indexes are needed to refer to a specific element within the tensor.

In [ ]:
#Each element along the first axis, is an array
dd[0]

[1, 2, 3]

In [ ]:
#Each element along the second axis, is a number
dd[0][1]

2

Note that, with tensors, the elements of the last axis are always numbers. Every other axis will contain n-dimensional arrays. This is what we see in this example, but this idea generalizes.

The rank of a tensor tells us how many axes a tensor has, and the length of these axes leads us to the very important concept known as the shape of a tensor.

### **Shape of a Tensor**

The shape of a tensor is determined by the length of each axis, so if we know the shape of a given tensor, then we know the length of each axis, and this tells us how many indexes are available along each axis.

The shape of a tensor gives us the length of each axis of the tensor.

Tensors have shapes.  Some vocabulary:

* **Shape**: The length (number of elements) of each of the dimensions of a tensor.
* **Rank**: Number of tensor dimensions.  A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor, the product shape vector

In [ ]:
# constant() is a function that helps you create a constant tensor
t= tf.constant(dd)
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
type(t)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
t.shape

TensorShape([3, 3])

In [ ]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

In [ ]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


Note: Although you may see reference to a "tensor of two dimensions", a rank-2 tensor does not usually describe a 2D space.

While axes are often referred to by their indices, you should always keep track of the meaning of each.
<table>
<tr>
<th>Typical axis order</th>
</tr>
<tr>
    <td>
<img src="https://github.com/tensorflow/docs/blob/master/site/en/guide/images/tensor/shape2.png?raw=1" alt="Keep track of what each axis is. A 4-axis tensor might be: Batch, Width, Height, Freatures">
  </td>
</tr>
</table>

In [ ]:
z = [9, 10, 11, 12]
new_z= tf.constant(z)
print(new_z.ndim)

1


# Tensor Operation Types
Before we dive in with specific tensor operations, let’s get a quick overview of the landscape by looking at the main operation categories that encompass the operations we’ll cover. We have the following high-level categories of operations:

1. Reshaping operations
2. Element-wise operations
3. Reduction operations
4. Access operations

In [ ]:
#reshaping without changing the rank
t = tf.constant([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=tf.float32) #mention the type of the element we want in the tensor


In [ ]:
# reshape is a function that helps to reshaping any ndarray or ndtensor
reshaped_tensor = tf.reshape(t, [1,12])     
print(reshaped_tensor)

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [ ]:
# reshape is a function that helps to reshaping any ndarray or ndtensor
reshaped_tensor = tf.reshape(t, [2,6])     
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1. 2. 2.]
 [2. 2. 3. 3. 3. 3.]], shape=(2, 6), dtype=float32)


In [ ]:
reshaped_tensor = tf.reshape(t, [3,4])     
print(reshaped_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]], shape=(3, 4), dtype=float32)


Using the `reshape()` function, we can specify the `row x column` shape that we are seeking. Notice how all of the shapes have to account for the number of elements in the tensor. In our example this is:



```
rows * columns = 12 elements
```

We can use the intuitive words rows and columns when we are dealing with a rank 2 tensor. The underlying logic is the same for higher dimensional tenors even though we may not be able to use the intuition of rows and columns in higher dimensional spaces. For example:

In [ ]:
reshaped_tensor= tf.reshape(t, [2,2,3])
print(reshaped_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 2. 2.]]

 [[2. 2. 3.]
  [3. 3. 3.]]], shape=(2, 2, 3), dtype=float32)


In this example, we increase the rank to 3, and so we lose the rows and columns concept. However, the product of the shape's components (2,2,3) still has to be equal to the number of elements in the original tensor ( 12).

## Changing Shape By Squeezing And Unsqueezing
The next way we can change the shape of our tensors is by squeezing and unsqueezing them.

1. Squeezing a tensor removes the dimensions or axes that have a length of one.
2. Unsqueezing a tensor adds a dimension with a length of one.

These functions allow us to expand or shrink the rank (number of dimensions) of our tensor.

In [ ]:
print(tf.reshape(t, [1,12]))

tf.Tensor([[1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]], shape=(1, 12), dtype=float32)


In [ ]:
#to obtain shape directly
print(tf.reshape(t, [1,12]).shape)

(1, 12)


In [ ]:
#squeezing
print(tf.squeeze(tf.reshape(t, [1,12])))

tf.Tensor([1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.], shape=(12,), dtype=float32)


In [ ]:
print(tf.squeeze(tf.reshape(t, [1,12])).shape)

(12,)


In [ ]:
print(tf.reshape(t, [2,6]))

tf.Tensor(
[[1. 1. 1. 1. 2. 2.]
 [2. 2. 3. 3. 3. 3.]], shape=(2, 6), dtype=float32)


In [ ]:
#it does not have an axes of 1
print(tf.squeeze(tf.reshape(t, [2,6])).shape)

(2, 6)



Let’s look at a common use case for squeezing a tensor by building a flatten function.

## Flatten A Tensor
A flatten operation on a tensor reshapes the tensor to have a shape that is equal to the number of elements contained in the tensor. This is the same thing as a 1d-array of elements.



```
Flattening a tensor means to remove all of the dimensions except for one.
```



In [ ]:
def flatten(t):
    t = tf.reshape(t, [1, -1])
    t = tf.squeeze(t)
    return t

Since the argument t can be any tensor, we pass -1 as the second argument to the reshape() function. In TensorFlow, the -1 tells the reshape() function to figure out what the value should be based on the number of elements contained within the tensor. Remember, the shape must equal the product of the shape's component values. This is how TensorFlow can figure out what the value should be, given a 1 as the first argument.

Since our tensor t has 12 elements, the reshape() function is able to figure out that a 12 is required for the length of the second axis.

After squeezing, the first axis (axis-0) is removed, and we obtain our desired result, a 1d-array of length 12.

In [ ]:
t = tf.ones([4, 3])
t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
flatten(t)

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

## Concatenating Tensors
We combine tensors using the `concat()` function, and the resulting tensor will have a shape that depends on the shape of the two input tensors.



In [ ]:
t1 = tf.constant([
    [1,2],
    [3,4]
])

t2 = tf.constant([
    [5,6],
    [7,8]
])

In [ ]:
# combining row-wise(axis=0)
tf.concat((t1, t2), axis = 0)  

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [ ]:
# combining column-wise (axis-1)
tf.concat((t1, t2), axis = 1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

When we concatenate tensors, we increase the number of elements contained within the resulting tensor. This causes the component values within the shape (lengths of the axes) to adjust to account for the additional elements.

In [ ]:
tf.concat((t1,t2), axis=0).shape

TensorShape([4, 2])

In [ ]:
tf.concat((t1,t2), axis=1).shape

TensorShape([2, 4])